# Assignment Day 3 | Data Science 101 B1

In [1]:
# Questions 1:
import numpy as np
# Create a numpy array starting from 2 till 50 with a stepsize of 3.
np.arange(1,50,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [2]:
# Questions 2:
# Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.
# 2,1,5,3,4
# 7,6,9,8,10
x = input('insert list 1 with , : ')
x = x.split(",")
x = [int(i) for i in x]
y = input('insert list 2 with , : ')
y = y.split(",")
y = [int(i) for i in y]

print(np.concatenate([x,y]))

x.sort()
y.sort()
print(x)
print(y)

print(np.concatenate([x,y]))

insert list 1 with , : 2,1,5,3,4
insert list 2 with , : 7,6,9,8,10
[ 2  1  5  3  4  7  6  9  8 10]
[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# Questions 3:
# Write a code snippet to find the dimensions of a ndarray and its size.
x = np.arange(12).reshape(3,4) # 2D array
y = np.arange(12) # 1D array


def dimAndSize(m):
    print(m)
    print('dimensions', m.ndim)
    print('size',m.shape)
    print('===================================')

dimAndSize(x)
dimAndSize(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
dimensions 2
size (3, 4)
[ 0  1  2  3  4  5  6  7  8  9 10 11]
dimensions 1
size (12,)


In [4]:
# Questions 4:
# How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet, Hint: np.newaxis, np.expand_dims
#1d
x = np.arange(1,50,3)
print(x)
print('dimensions',x.ndim)
print('===================================')
# 2d with expand_dims
y1 = np.expand_dims(x, axis=0)
print(y1)
print('dimensions',y1.ndim)

y2 = np.expand_dims(x, axis=1)
print(y2)
print('dimensions',y2.ndim)
print('===================================')
# 2d with newaxis
z1 = x[np.newaxis, :]
print(z1)
print('dimensions',z1.ndim)

z2 = x[:, np.newaxis] 
print(z2)
print('dimensions',z2.ndim)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]
dimensions 1
[[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]]
dimensions 2
[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]
 [19]
 [22]
 [25]
 [28]
 [31]
 [34]
 [37]
 [40]
 [43]
 [46]
 [49]]
dimensions 2
[[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]]
dimensions 2
[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]
 [19]
 [22]
 [25]
 [28]
 [31]
 [34]
 [37]
 [40]
 [43]
 [46]
 [49]]
dimensions 2


In [5]:
# Questions 5:
# Consider two square numpy arrays. Stack them vertically and horizontally. Hint: Use vstack(), hstack()
x = np.ones((3,3))
y = np.zeros((3,3))

print(np.vstack((x,y)))
print('======================')
print(np.hstack((x,y)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]]


In [6]:
# Questions 6:
# How to get unique items and counts of unique items?
x = np.array([2,2,1,4,3,5,3,5,9,8,4])
y = np.unique(x)
print(y)
z = np.unique(x,return_counts=True)
print(z)

[1 2 3 4 5 8 9]
(array([1, 2, 3, 4, 5, 8, 9]), array([1, 2, 2, 2, 2, 1, 1], dtype=int64))
